// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfConfigT struct {
	Uid uint32
	Pid int32
}

type bpfEventDataT struct {
	Begin uint64
	Pid   uint32
	Size  uint32
}

type bpfMethodEventDataT struct {
	Begin        uint64
	Pid          uint32
	Size         uint32
	ArtMethodPtr uint64
	MethodIndex  uint32
	_            [4]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	UprobeLibartExecute          *ebpf.ProgramSpec `ebpf:"uprobe_libart_execute"`
	UprobeLibartExecuteNterpImpl *ebpf.ProgramSpec `ebpf:"uprobe_libart_executeNterpImpl"`
	UprobeLibartVerifyClass      *ebpf.ProgramSpec `ebpf:"uprobe_libart_verifyClass"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConfigMap       *ebpf.MapSpec `ebpf:"config_map"`
	DexFileCacheMap *ebpf.MapSpec `ebpf:"dexFileCache_map"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	MethodEvents    *ebpf.MapSpec `ebpf:"method_events"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConfigMap       *ebpf.Map `ebpf:"config_map"`
	DexFileCacheMap *ebpf.Map `ebpf:"dexFileCache_map"`
	Events          *ebpf.Map `ebpf:"events"`
	MethodEvents    *ebpf.Map `ebpf:"method_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.DexFileCacheMap,
		m.Events,
		m.MethodEvents,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	UprobeLibartExecute          *ebpf.Program `ebpf:"uprobe_libart_execute"`
	UprobeLibartExecuteNterpImpl *ebpf.Program `ebpf:"uprobe_libart_executeNterpImpl"`
	UprobeLibartVerifyClass      *ebpf.Program `ebpf:"uprobe_libart_verifyClass"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.UprobeLibartExecute,
		p.UprobeLibartExecuteNterpImpl,
		p.UprobeLibartVerifyClass,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
